select *
from MEMBER;

DROP TABLE TB_FILE;
CREATE TABLE TB_FILE(
	IDX NUMBER,
	PARENT_SEQ NUMBER NOT NULL,
	ORIGINAL_FILE_NAME VARCHAR2(260 BYTE) NOT NULL,
	STORED_FILE_NAME VARCHAR2(36) NOT NULL,
	FILE_SIZE NUMBER,
	CRE_DATE DATE NOT NULL,
	PRIMARY KEY (IDX)
);

DROP SEQUENCE TB_FILE_IDX_SEQ;
CREATE SEQUENCE TB_FILE_IDX_SEQ
START WITH 1
INCREMENT BY 1;

INSERT INTO TB_FILE
	(IDX, PARENT_SEQ, ORIGINAL_FILE_NAME,
	STORED_FILE_NAME, FILE_SIZE, CRE_DATE)
VALUES(
	TB_FILE_IDX_SEQ.nextval, 1, '파일.TXT', 
	'UNIQUE_VALUE', 1024, SYSDATE
);

COMMIT
rollback

SELECT *
FROM TB_FILE;

delete from TB_FILE;




